# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ParseStarterProject-Swift' do
    pod 'Parse', '~> 1.10'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'ParseFacebookUtilsV4', '~> 1.9'

    workspace 'wandoo'
end

